server :
  port : 8080
  servlet:
    context-path: /
    encoding:
      enabled : true
      charset : UTF-8
      force : true
    session :
      timeout : 18000

  tomcat :
    uri_encoding : UTF-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/library
    driver-class-name: org.mariadb.jdbc.Driver
    username: librarian
    password: rmsoft
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      physical_naming_strategy : com.book.manage.config.CustomPhysicalNamingStrategy
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
logging:
  level:
    org.hibernate.type : trace